### Register
POST http://localhost:3000/user/register
content-type: application/json

{
    "username":"kamil",
    "password":"1234",
    "lastName":"Adam",
    "firstName":"Kami"
    
}

### Login
POST http://localhost:3000/user/login
content-type: application/json

{
    "username":"kamil",
    "password":"1234"
}


### Get all posts
GET http://localhost:3000/api/posts


### Hello world to server
GET http://localhost:3000/

###Send new post
POST http://localhost:3000/api/posts
content-type: application/json

{
    "title":"Kamil123-test",
    "content":"bla blab bla blabbla blabbla blab"
}

###Create new Family
POST http://localhost:3000/family/new
content-type: application/json

{
    "familyName":"Wimau"
}

###Create new Family
GET  http://localhost:3000/family/
content-type: application/json
