### Register
POST http://localhost:3000/user/register
content-type: application/json

{
    "username":"kamil2",
    "password":"1234",
    "lastName":"Adam",
    "firstName":"Kami"
    
}

### Login
POST http://localhost:3000/user/login
content-type: application/json

{
    "username":"kamil2",
    "password":"1234"
}


### Get all posts
GET http://localhost:3000/api/posts


### Hello world to server
GET http://localhost:3000/

###Send new post
POST http://localhost:3000/api/posts
content-type: application/json

{
    "title":"Kamil123-test",
    "content":"bla blab bla blabbla blabbla blab"
}

###Create new Family
POST http://localhost:3000/family
content-type: application/json

{
    "familyName":"Soprano22"
}

###GET ALL new Family
GET  http://localhost:3000/family
content-type: application/json

###Show family by ID
GET  http://localhost:3000/family/62bd6cf951fc80cef7877c22
content-type: application/json


### Remove user
DELETE   http://localhost:3000/user/62bd6cf351fc80cef7877c1c
content-type: application/json


### Join Family
PATCH  http://localhost:3000/family/join/62bd6cf951fc80cef7877c22

### Quit Family
PATCH  http://localhost:3000/family/quit/62bd6cf951fc80cef7877c22


###SHAKEHAND - get current user info
GET  http://localhost:3000/user/shakehand
content-type: application/json

###Show my family
GET  http://localhost:3000/user/myfamily
content-type: application/json

### Set Bugdet for Family
PATCH  http://localhost:3000/family/62bd8b6fe9d49e4224a08558/budget
content-type: application/json

{
    "budgetValue":2000
}