###GET - find latest families created
GET  http://localhost:3000/families
content-type: application/json


###POST - Create new Family
POST http://localhost:3000/families
content-type: application/json

{
    "familyName":"Sporano007ł"
}


###GET - find some specific family
GET  http://localhost:3000/families/62bd6cf951fc80cef7877c22
content-type: application/json


### Join Family
PATCH  http://localhost:3000/families/62bd6cf951fc80cef7877c22/join

### Quit Family
PATCH  http://localhost:3000/families/62bd6cf951fc80cef7877c22/quit


### Set Bugdet for Family
PATCH  http://localhost:3000/families/62beef308ad39ae133c0df95/budget
content-type: application/json

{
    "budgetValue":5000
}

### Add Expense for Family
POST  http://localhost:3000/families/62bd6cf951fc80cef7877c22/expenses
content-type: application/json

{
    "value":1500,
    "name":"else"
}

### Remove Expense form Family
DELETE  http://localhost:3000/families/62bd6cf951fc80cef7877c22/expenses/62bf11d3013c7782a38fc5fd
content-type: application/json

### Edit Expense form Family
PATCH  http://localhost:3000/families/62bd6cf951fc80cef7877c22/expenses/62bf11d3013c7782a38fc5fd
content-type: application/json

{
    "name":"new_Name"
}