
### Login
POST http://localhost:3000/login
content-type: application/json

{
    "username":"monipopi",
    "password":"1234"
}


### Register
POST http://localhost:3000/register
content-type: application/json

{
    "username":"monipopi2",
    "firstName":"Monika",
    "lastName":"Kołon",
    "password":"1234"
}

