### POST - Log in user
POST http://localhost:3000/user/login
content-type: application/json

{
    "username":"monipopi",
    "password":"1234"
}

### GET - Get user information from user with Given ID
GET  http://localhost:3000/user/62bd6d4451fc80cef7877c36
content-type: application/json

### DELETE - Remove user with given ID
DELETE   http://localhost:3000/user/62bddd2b28c5126a6715b866
content-type: application/json


### PUT - Create new user (Register)
PUT  http://localhost:3000/user/register
content-type: application/json

{
    "username":"monipopi2",
    "firstName":"Monika",
    "lastName":"Kołon",
    "password":"1234"
}



# ###Show my family
# GET  http://localhost:3000/user/myfamily
# content-type: application/json