### POST - Log in user
POST http://localhost:3000/user/login
content-type: application/json

{
    "username":"johny",
    "password":"1234"
}

### Check is looged in
GET http://localhost:3000/user/loggedincheck



### POST - Logout
POST http://localhost:3000/user/logout
content-type: application/json


### GET - get all userd
GET http://localhost:3000/user/
content-type: application/json

### GET - myProfile
GET http://localhost:3000/user/myprofile
content-type: application/json


### GET - Get user information from user with Given ID
GET  http://localhost:3000/user/62c028a09830571d4d4c45c7
content-type: application/json



### DELETE - Remove user with given ID
DELETE   http://localhost:3000/user/62bddd2b28c5126a6715b866
content-type: application/json



### PUT - Create new user (Register)
POST  http://localhost:3000/user/register
content-type: application/json

{
    "username":"johny1axdac2cvs",
    "firstName":"John",
    "lastName":"Bravo",
    "password":"1234"
}