### POST - Log in user
POST http://localhost:3000/user/login
content-type: application/json

{
    "username":"monipopi",
    "password":"1234"
}



### POST - Logout
POST http://localhost:3000/user/logout
content-type: application/json



### GET - Get user information from user with Given ID
GET  http://localhost:3000/user/62bde7bd6b2bf2dd8f806e8fs
content-type: application/json



### DELETE - Remove user with given ID
DELETE   http://localhost:3000/user/62bddd2b28c5126a6715b866
content-type: application/json



### PUT - Create new user (Register)
POST  http://localhost:3000/user/register
content-type: application/json

{
    "username":"monipopi",
    "firstName":"Monika",
    "lastName":"Kołon",
    "password":"1234"
}